/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.TrainService;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Train system app is running");
        Scanner sc = new Scanner(System.in);
        UserBookingService ubs ;
        try{
             ubs=new UserBookingService();}
        catch(IOException e){
            System.out.println(e.getMessage());
            return;
        }
        int option=0;
        Train trainSelectedForBooking = null;
        User loggedInUser = null;
        String source = "";
        String dest = "";
        while(option!=7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = sc.nextInt();
            switch (option){
                case 1:  System.out.println("Enter the username to signup");
                    String nameToSignUp = sc.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = sc.next();
                    User user=new User(UUID.randomUUID().toString(),new ArrayList<Ticket>(), UserServiceUtil.hashpassword(passwordToSignUp),passwordToSignUp,nameToSignUp);
                    ubs.signUp(user);
                    System.out.println("Signup completed!!");
                    break;
                case 2:  System.out.println("Enter the username to login");
                    String name = sc.next();
                    System.out.println("Enter the password to login");
                    String password = sc.next();
                    loggedInUser=ubs.loginUser(name,password);
                    if (loggedInUser != null) {
                        ubs.setLoggedInUser(loggedInUser); // Set the user in the service
                        System.out.println("LOGGED IN SUCCESSFULLY");
                    } else {
                        System.out.println("Login failed. Invalid username or password.");
                    }
                    break;
                case 3: System.out.println("Fetching your bookings");
                        ubs.fetchBookings();
                        break;
                case 4:System.out.println("Type your source station");
                      source = sc.next();
                      System.out.println("Type your destination station");
                      dest = sc.next();
                      List<Train> trains;
                    try{
                        trains= ubs.getTrains(source,dest);} catch (IOException e) {
                        System.out.println("Error occured while searching, Retry");
                        break;
                    }
                    if(trains.isEmpty()){
                        System.out.println("No trains are available for this route");
                        break;
                    }
                    for(int i=0;i<trains.size();i++) {
                        Train t = trains.get(i);
                        System.out.printf("Train Number: %s Train id: %s", t.getTrainNo(), t.getTrainId());
                    }
                        System.out.println("Select a train by typing 1,2,3...");
                        int choice=sc.nextInt();
                    if (choice > 0 && choice <= trains.size()) {
                        trainSelectedForBooking = trains.get(choice - 1);
                        System.out.println("Train " + trainSelectedForBooking.getTrainId() + " selected.");
                    } else {
                        System.out.println("Invalid selection.");
                    }
                        trainSelectedForBooking=trains.get(choice);
                    break;
                case 5:
                    if (loggedInUser == null) {
                        System.out.println("Please login first.");
                        break;
                    }
                    if (trainSelectedForBooking == null) {
                        System.out.println("Please search and select a train first (Option 4).");
                        break;
                    }
                    System.out.println("Select a seat out of these seats");
                    try{
                        List<List<Integer>> seats = ubs.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat....");
                    Ticket bookedTicket=ubs.bookSeat(trainSelectedForBooking, row, col,source,dest);
                        if(bookedTicket != null) {
                            System.out.println("Booked! Enjoy your journey.");
                            System.out.println("Your Ticket ID is: " + bookedTicket.getTicketId());
                        }else {
                            System.out.println("Could not book this seat.");
                        }
                    } catch (Exception e) {
                        System.out.println("An error occurred during booking: " + e.getMessage());
                    }
                    break;
                case 6:System.out.println("Enter ur Ticket-ID");
                       String id=sc.next();
                       boolean cancel=ubs.cancelBooking(id);
                       if(cancel){
                           System.out.println("Cancellation of Booking has been successfull!!");
                           break;
                       }
                       else{
                           System.out.println("Cancellation failed");
                       }
                       break;
                default:
                    break;
            }

        }
    }
}
